### PR TITLE
Validate lbrycrd addresses

### PR DESCRIPTION
**Pull request by jackrobison**
Currently only the length of a lbrycrd address is checked. This adds validation for the checksum and prefix byte. Additionally, since base.py was only used to decode and encode base58 addresses, I renamed the filename and encode/decode functions to be more descriptive, removed the redundant `base` argument (always 58), and changed the functions to raise an error if nothing can be decoded (which previously returned None and was detected and handled by raising an error in whatever called encode/decode).

This also requires an update to lbrynet (Daemon.py) to match the updated import path for `decode_address`.

### CODE REVIEW

**Comment by kaykurokawa** [comment]
is this basically just copied over from lbryum?

**Comment by jackrobison** [comment]
@kaykurokawa Essentially, yes.The issue in lbryschema is primarily that invalid addresses could make their way into claims in the fee address field. Additionally, the address validation check by lbrynet-daemon in `wallet_send` uses lbryschema. It could use lbryum instead (where it has been fixed), but it needs to be fixed here too.

**Comment by kauffj** [comment]
You are breaking one of [the coding maxims](https://gist.github.com/lyoshenka/0a43205aa9a072b196ff87e2c689a8b9). Get him @lyoshenka!

**Comment by lyoshenka** [comment]
☹️ ☹️ ☹️ ☹️ ☹️ ☹️

**Comment by jackrobison** [comment]
@kauffj until we split out the transaction/address parsing, serialization, and validation logic out of lbryum and into a repo that can be shared between lbryschema, lbryum, and lbryum server violations to DRY are hard to avoid - otherwise there would be a dependency loop. :(

**Pull request merged**
