### PR TITLE
Changed the minimum claim length.

### PR DESCRIPTION
**Pull request by hackrush01**
Now the minimum channel length is set to 1

Fixes [lbry#769](https://github.com/lbryio/lbry/issues/769)

### CODE REVIEW

**Comment by hackrush01** [comment]
@kauffj @jackrobison

**Comment by lyoshenka** [comment]
Sorry

**Comment by hackrush01** [comment]
I'll look into it.

**Comment by hackrush01** [comment]
Closed by accident.

**Comment by jackrobison** [comment]
LGTM

**Comment by kauffj** [comment]
@jackrobison if a PR looks good to you, you can just merge it. One review is sufficient, unless you think it is particularly complex or you have some doubts with regards to your assessment.

I'm going to merge this now.

**Pull request merged**
