### PR TITLE
fixed generate_test_data.py which was not generating malformed_secp256k1_cert and hex_encoded_003

### PR DESCRIPTION
**Pull request by KamilPiekutowski**
Once the generate_test_data.py was run it would break the testing sequence. Now it can be run and test will go on.

### CODE REVIEW

**Comment by lyoshenka** [comment]
@KamilPiekutowski thanks for the PR. One of our devs will review it shortly. Also see https://lbry.io/faq/tips for an LBC tip :-)

**Comment by KamilPiekutowski** [comment]
With length element daemon does not deserialize metadata. I am still investigating why.

**Comment by KamilPiekutowski** [comment]
Please check if this does not break deamon. When you run cli claim_list_mine the metadata should be properly deserialized int json. If not then I just fixed it with the next commit.

**Comment by jackrobison** [comment]
@KamilPiekutowski thanks for the contribution!

Can you split the addition of the length field from the generate_test_data fix into another pr?

Regarding the length addition:
 - `lbryschema.legacy` contains the old json schema and migrates from it, you shouldn't need to add anything to it.
 - I think `contentLength` should be a optional attribute (type int) of `Source` (lbryschema/proto/source.proto) rather than `Metadata`, since `contentType` is already in there.

@lyoshenka should `contentLength` be required or optional?

**Comment by kauffj** [comment]
`contentLength` is optional, and should be an integer representing the length of the content in milliseconds.

**Comment by KamilPiekutowski** [comment]
Thanks. I will work on asap.

**Comment by jackrobison** [comment]
@kauffj 

Shouldn't it be the length in bytes? What about for non-video streams?

**Comment by kauffj** [comment]
This field is specifically for the time length of video or audio content. It should likely have a name that indicates it is a time based field, such as `contentDuration`, rather than `contentLength`, to make this clear.

**Comment by KamilPiekutowski** [comment]
@jackrobison We could also add content size that it would require on disk.

**Comment by KamilPiekutowski** [comment]
@jackrobison Can you please let me know how to split this pull request into two parts? I have not done it before.

**Comment by tzarebczan** [comment]
Kamil, you'll need to revert the commit you have for the tests and create a separate PR for those changes. Typically PRs should only accomplish a single goal.

**Comment by KamilPiekutowski** [comment]
Ok so removed last 3 commits. I did not want them anyway since @jackrobison  suggested a proper approach. I am going to look into that right now, but before I start. Should I create new pull request right now so the next commits go in there?

**Comment by KamilPiekutowski** [comment]
@tzarebczan I think I was able to split this pr but I am not sure if it is correct. Other changes that involve content duration are in this pr [https://github.com/lbryio/lbryschema/pull/24](url)

**Comment by tzarebczan** [comment]
Closing this one per Kamil, was split into: https://github.com/lbryio/lbryschema/pull/24

**Comment by KamilPiekutowski** [comment]
Done

**Comment by KamilPiekutowski** [comment]
How do I change permissions ?

**Pull request closed without merging**
